# 代码优雅之道:简化异常处理语句

异常处理

## 方式

## 先来个实际效果

写代码时难免会遇到异常, 对待异常有的时候直接抛出, 有的时候需要实际的处理, 例如下面这个

![图 1](https://gitee.com/cpfree/picture-warehouse/raw/master/images/common/1f0859f4bcb59a20d009e99105acd92a3aaab34e54078cb225a74510a0dce204.png)  

MessageDigest 里面是有MD5方法的, 那么这个异常完全没必要, 那就在方法内部对异常进行处理, 然后就变成了下面这样.

```java
    /**
     * 获取一个byte[]的md5值
     *
     * @param data 待转换的数据
     * @return md5 byte[]的MD5值
     */
    public static String getMD5(byte[] data) {
        MessageDigest md5;
        try {
            md5 = MessageDigest.getInstance("MD5");
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("MessageDigest 未发现 MD5 方法", e);
        }
        byte[] digest = md5.digest(data);
        return new BigInteger(1, digest).toString(16);
    }
```

本来三行就能写好的代码, 因为个异常处理变得臃肿, 难看, 那么有没有办法把它变得优雅呢?

答案肯定有, 否则就不会有这篇文章了!

为了节省大家的时间, 首先来展示下优化后的代码.

```java
    /**
     * 获取一个byte[]的md5值
     *
     * @param data 待转换的数据
     * @return md5 byte[]的MD5值
     */
    public static String getMD5(byte[] data) {
        final MessageDigest md5 = Throws.fun("MD5", MessageDigest::getInstance).runtimeExp("MessageDigest 未发现 MD5 方法").value();
        byte[] digest = md5.digest(data);
        return new BigInteger(1, digest).toString(16);
    }
```

3行搞定真是很开心!

其实不只是上面的优化, 也能做到下面几组的优化

第一组优化

   ```java
      // 源代码
      String s = null;
      try {
         s = ConfigTest.newHaha();
      } catch (NoSuchMethodException e) {
         log.error("", e);
      }

      // == SimpleCode优化
      String s = SimpleCode.ignoreException(ConfigTest::newHaha);

      // == Throws 优化
      String s = Throws.sup(ConfigTest::newHaha).logThrowable().value();
   ```

第二组优化

   ```java
      try {
         AppContext.init()
      } catch (ConfigException e) {
         e.printStackTrace();
      }

      // 等价于
      
      Throws.con(100, AppContext::init).catchToPrintStackTrace();
      
      // 或等价于
      
      Throws.run(() -> AppContext.init()).catchToPrintStackTrace();
   ```

---

## 异常语句优化思路

在写工具类的时候, 很多情况下, 对异常的处理也就是个`打印现场`工作, 即便写业务类也就是个`打印现场`, 既然工作都差不多, 那就可以想办法封装起来, 优化代码, 又便于阅读.

首先, 说到封装`try catch`, 能够想到的就是`函数式接口`和`lambda表达式`, 这真是JAVA的两大神器啊!

然后, JDK自带的函数式接口是没有办法处理异常的, 那就把之前说到的几个带有异常抛出的几个函数式接口拿出来.

   ![图 2](https://gitee.com/cpfree/picture-warehouse/raw/master/images/common/497e7174b971f78f710b654b8057b0b68eb3109f0f77241dcfddb7d6a42860ae.png)

那么, 就很容易想到一种方式, 通过静态方法, 将lambda表达式当作参数传进去, 在静态方法里面处理异常, 这样就可以简化异常的代码.

其次, 讲到 `try catch` 比较好的处理方式, 我想到的是JS里面的 `Promise`, 它的处理方式给我带来了很多灵感.

接下来, 就通过代码实际操作一下吧!

## 异常语句优化方式1-静态方法优化

由于涉及到好几个lambda表达式的优化, 整体代码较多, 下面只是展示下 SupplierWithThrow 的优化方式

   > RunnableWithThrow : 带有抛出异常的 Runnable 接口
   > SupplierWithThrow : 带有抛出异常的 Supplier 接口
   > ConsumerWithThrow : 带有抛出异常的 Consumer 接口
   > FunctionWithThrow : 带有抛出异常的 Function 接口

1. 首先, 下面是 SupplierWithThrow.java 代码

   ```java
   /**
   * <b>Description : </b> 带有抛出异常的 Supplier 接口
   * <p>
   * <b>created in </b> 2020/6/29
   *
   * @author CPF
   * @see java.util.function.Supplier
   * @since 1.0
   */
   @FunctionalInterface
   public interface SupplierWithThrow<T, E extends Throwable> {

      T get() throws E;
   }
   ```

2. 为了简化异常的处理, 我将异常的通用处理方式分为以下两类

   1. 打印现场日志: 打印现场信息, 以及标记, 用于快速了解异常原因和相关信息.
   2. RuntimeException化: 为了简化一些异常, 这里将编译时异常转换为运行时异常抛出, 同时可以将更多的现场信息也一并携带抛出.

   如此静态方法酒由

   ```java
   package com.github.cosycode.common.ext.hub;

   import com.github.cosycode.common.base.ConsumerWithThrow;
   import com.github.cosycode.common.base.RunnableWithThrow;
   import com.github.cosycode.common.base.SupplierWithThrow;
   import com.github.cosycode.common.lang.ActionExecException;
   import lombok.extern.slf4j.Slf4j;

   /**
   * <b>Description : </b> 简化代码类, 对冗余的代码进行简化, 增强可读性
   * <p>
   * ignoreException开头, 忽略发生的异常, 仅仅打印日志.
   * <p>
   * runtimeException开头, 原来需要catch的运行时转换为runtimeException抛出
   * <p>
   * <b>created in </b> 2020/6/24
   *
   * @author CPF
   * @since 1.0
   */
   @Slf4j
   public class SimpleCode {
      /**
      * 简化编译时异常代码方法
      *
      * @param supplier       带有返回值和throw的函数接口
      * @param defaultValue   throwException为true时, supplier 发生错误后的默认返回值
      * @param message        supplier 发生错误后的信息
      * @param throwException true: supplier 发生错误后抛出运行时异常, false: 仅仅打印日志
      * @param <T>            supplier的提供的返回值类型
      * @return supplier 执行成功: supplier的返回值, supplier 执行失败: 返回 defaultValue
      */
      public static <T> T simpleExceptionForSup(SupplierWithThrow<T, ? extends Exception> supplier, T defaultValue, String message, boolean throwException) {
         try {
               return supplier.get();
         } catch (Exception e) {
               if (throwException) {
                  // ActionExecException 是在我的jar包中对 RuntimeException 的一个封装, 直接理解为 RuntimeException 就行
                  throw new ActionExecException(message, e);
               } else {
                  log.warn(message, e);
               }
         }
         return defaultValue;
      }

      /**
      * 忽略运行的异常, 仅打印异常日志, 
      *
      * @param supplier     带有返回值和throw的函数接口
      * @param defaultValue supplier 发生错误后的默认返回值
      * @param message      发生错误后打印抛出的异常信息
      * @param <T>          supplier的提供的返回值类型
      * @return supplier 的返回值
      */
      public static <T> T ignoreException(SupplierWithThrow<T, ? extends Exception> supplier, T defaultValue, String message) {
         return simpleExceptionForSup(supplier, defaultValue, message, false);
      }

      /**
      * 原来需要 catch 的运行时转换为 runtimeException 抛出
      *
      * @param supplier 带有返回值和throw的函数接口
      * @param message  supplier 发生错误后的信息
      * @param <T>      supplier的提供的返回值类型
      * @return supplier 的返回值
      * @see SimpleCode#simpleExceptionForSup(SupplierWithThrow, java.lang.Object, java.lang.String, boolean)
      */
      public static <T> T runtimeException(SupplierWithThrow<T, ? extends Exception> supplier, String message) {
         return simpleExceptionForSup(supplier, null, message, true);
      }

   }
   ```

3. 如此下面的代码就可以这样优化了

   ```java
      /**
      * 获取一个byte[]的md5值
      *
      * @param data 待转换的数据
      * @return md5 byte[]的MD5值
      */
      public static String getMD5(byte[] data) {
         MessageDigest md5;
         try {
               md5 = MessageDigest.getInstance("MD5");
         } catch (NoSuchAlgorithmException e) {
               throw new RuntimeException("MessageDigest 未发现 MD5 方法", e);
         }
         byte[] digest = md5.digest(data);
         return new BigInteger(1, digest).toString(16);
      }
   ```

   优化为

   ```java
      /**
      * 获取一个byte[]的md5值
      *
      * @param data 待转换的数据
      * @return md5 byte[]的MD5值
      */
      public static String getMD5(byte[] data) {
         MessageDigest md5 = SimpleCode.runtimeException(() -> MessageDigest.getInstance("MD5"), "MessageDigest 未发现 MD5 方法");
         byte[] digest = md5.digest(data);
         return new BigInteger(1, digest).toString(16);
      }
   ```

4. 分析

   通过静态方法去对异常进行处理可以有效简化代码, 方便阅读.
   但是在使用过程中却需要在方法中传入很多参数, 而且使用过程很不灵活.
   而且SimpleCode类重载方法太多, 而且难以扩展, 如果想要对异常的处理方式进行改动, 那么就需要更换很多个重载方法.

## 异常语句优化方式2-Throws对象优化

> 灵感来源于 Js 的 Promise对象处理

由于涉及到好几个lambda表达式的优化, 整体代码较多, 下面只是展示下 RunnableWithThrow 的优化方式

1. 首先, 下面是 RunnableWithThrow.java 代码

   ```java
   /**
   * <b>Description : </b> 带有抛出异常的 Runnable 接口
   * <p>
   * <b>created in </b> 2020/6/29
   *
   * @author CPF
   * @see java.lang.Runnable
   * @since 1.0
   */
   @FunctionalInterface
   public interface RunnableWithThrow<E extends Throwable> {

      void run() throws E;

   }
   ```

2. 废话不多说, 直接上代码, 下面只是 Throws 类中的关于 RunnableWithThrow 的代码

   ```java
   package com.github.cosycode.common.ext.hub;

   import com.github.cosycode.common.base.ConsumerWithThrow;
   import com.github.cosycode.common.base.FunctionWithThrow;
   import com.github.cosycode.common.base.RunnableWithThrow;
   import com.github.cosycode.common.base.SupplierWithThrow;
   import com.github.cosycode.common.lang.RuntimeExtException;
   import lombok.AccessLevel;
   import lombok.Getter;
   import lombok.NoArgsConstructor;
   import lombok.NonNull;
   import lombok.extern.slf4j.Slf4j;

   import java.util.Optional;
   import java.util.function.Consumer;

   /**
   * <b>Description : </b> 异常处理精简类, 该类旨在简化代码结构, 并没有添加太多功能.
   * <p> 一般用于个人项目, 或者是很难出错的语句, 不建议在生产环境使用
   * <b>created in </b> 2021/3/30
   *
   * @author CPF
   * @since 1.0
   **/
   @NoArgsConstructor(access = AccessLevel.PRIVATE)
   @Slf4j
   public class Throws {

      /**
      * <b>Description : </b> 异常封装处理Bean, 用于没有返回值的异常封装
      * <p>
      * <p> 类中使用了链式调用, 其中的很多方法在执行之后都会返回其自身
      * <b>created in </b> 2021/3/30
      *
      * @author CPF
      * @since 1.3
      **/
      public static class PromiseForRunnable<E extends Exception> {

         @Getter
         protected Exception throwable;

         /**
            * 如果是 private的话, 子类之外无法调用该方法
            */
         void setThrowable(Exception throwable) {
               this.throwable = throwable;
         }

         /**
            * 如果有异常, 则对异常进行处理
            * <p>该方法中 E 不应该是runtimeException中的子类, 由于java语言特性, 在此很难直接通过语法进行限制.</p>
            * <p>但是我觉得, 应该不会有人在方法上直接声明 throw RuntimeException 及其子类吧 </p>
            *
            * @param throwableConsumer 异常处理方法
            * @return 链式调用, 返回对象本身
            */
         public PromiseForRunnable<E> catCh(Consumer<E> throwableConsumer) {
               if (this.throwable != null) {
                  if (this.throwable instanceof RuntimeException) {
                     log.debug("throwable: {} 不应该是 RuntimeException 的子类, 建议不要声明 throws RuntimeException 及其子类", this.throwable.getClass());
                  } else {
                     throwableConsumer.accept((E) this.throwable);
                  }
               }
               return this;
         }

         /**
            * 对指定异常进行捕获
            *
            * @param throwableConsumer 异常处理方法
            * @return 链式调用, 返回对象本身
            */
         public <T extends E> PromiseForRunnable<E> catCh(@NonNull Class<T> catchEptType, Consumer<T> throwableConsumer) {
               if (catchEptType.isInstance(this.throwable)) {
                  throwableConsumer.accept((T) this.throwable);
               }
               return this;
         }

         /**
            * 如果有异常, 则对异常进行处理
            *
            * @param throwableConsumer 异常处理方法
            * @return 链式调用, 返回对象本身
            */
         public PromiseForRunnable<E> catchAll(Consumer<Exception> throwableConsumer) {
               if (this.throwable != null) {
                  throwableConsumer.accept(this.throwable);
               }
               return this;
         }

         /**
            * 使用JDK自带函数打印异常堆栈
            */
         public PromiseForRunnable<E> catchToPrintStackTrace() {
               if (this.throwable != null) {
                  this.throwable.printStackTrace();
               }
               return this;
         }

         /**
            * 如果有异常则打印异常信息
            */
         public PromiseForRunnable<E> logThrowable() {
               if (this.throwable != null) {
                  log.error("", this.throwable);
               }
               return this;
         }

         /**
            * 如果有异常则打印异常信息
            *
            * @param message 异常标记文本
            */
         public PromiseForRunnable<E> logThrowable(String message) {
               if (this.throwable != null) {
                  log.error(message, this.throwable);
               }
               return this;
         }

         /**
            * 将非运行时异常封装到运行时异常并抛出
            */
         public PromiseForRunnable<E> runtimeExp() {
               if (this.throwable != null) {
                  throw new RuntimeExtException(this.throwable);
               }
               return this;
         }

         /**
            * 将非运行时异常封装到运行时异常并抛出
            *
            * @param message 异常文本
            */
         public PromiseForRunnable<E> runtimeExp(String message) {
               if (this.throwable != null) {
                  throw new RuntimeExtException(message, this.throwable);
               }
               return this;
         }

         /**
            * 如果执行成功, 则执行 runnable
            *
            * @param runnable 执行函数
            */
         public PromiseForRunnable<E> then(Runnable runnable) {
               if (this.throwable == null) {
                  runnable.run();
               }
               return this;
         }

      }

      /**
      * 对异常进行后续封装处理
      *
      * @param runnable 运行函数
      * @param <E>      需要抛出的异常
      * @return 对函数之后后的异常进行捕获, 并封装成类
      */
      public static <E extends Exception> PromiseForRunnable<E> run(RunnableWithThrow<E> runnable) {
         PromiseForRunnable<E> promise = new PromiseForRunnable<>();
         try {
               runnable.run();
         } catch (Exception e) {
               promise.setThrowable(e);
         }
         return promise;
      }

      /**
      * 对异常进行后续封装处理
      *
      * @param p        运行函数参数
      * @param consumer 运行函数
      * @param <P>      函数接口参数类型
      * @param <E>      需要抛出的异常
      * @return 对函数之后后的异常进行捕获, 并封装成类
      */
      public static <P, E extends Exception> PromiseForRunnable<E> con(P p, ConsumerWithThrow<P, E> consumer) {
         PromiseForRunnable<E> promise = new PromiseForRunnable<>();
         try {
               consumer.accept(p);
         } catch (Exception e) {
               promise.setThrowable(e);
         }
         return promise;
      }
   }
   ```

3. 如此下面的代码就可以这样优化了

   ```java
      try {
         AppContext.init("classpath:app-context.xml")
      } catch (ConfigException e) {
         e.printStackTrace();
      }
   ```

   优化为

   ```java
      Throws.run(() -> AppContext.init("classpath:app-context.xml")).catchToPrintStackTrace();

      或者

      Throws.con("classpath:app-context.xml", AppContext::init).catchToPrintStackTrace();
   ```

4. 分析

   这种方法相对来讲比较灵活, 也能够有效减少代码.
   但是, 这种方法, 每次在调用的时候都是会创建一个实例对象, 多占用一点内存.
   而且, 在实际使用过程中, 不小心就会忘记调用catchToPrintStackTrace()等异常处理方法, 对异常进行处理, 当然这个实际上是可以设定一个默认异常处理方式, 或者在建立对象时, 就多传入一个异常处理参数.

---

关于这种简化异常代码的方式, 优点是简化代码, 便于阅读, 但是也有缺点, 例如, 不知道的人就有些看不懂这种方式, 而且, 对于需要一些处理逻辑的异常, 是不推荐这种方式简化的.

第一开始在想到这种异常简化的方式的时候, 我有些觉得这种方式只能在测试或者是在个人业余项目上使用, 在实际项目开发中是不推荐使用的.

所以第一开始也没怎么在意, 仅仅为了好玩, 将它写了出来.

但是之后每次遇到异常处理的时候, 尤其是那些简单的异常处理, 都会想到这个代码简化.

后来试着用了几下, 然后就感觉收不住了, 现在我自己的业余代码里面使用的大多都是这种方式, 至少我觉得太香了.
